name 'olyn_git'
maintainer 'Scott Richardson'
maintainer_email 'dev@grogwood.com'
chef_version '~> 16'
license 'GPL-3.0'
supports 'debian', '>= 10'
source_url 'https://gitlab.com/olyn/olyn_git'
description 'Installs and configures Git and remote repos locally on the server'
version '1.0.4'

provides 'olyn_git::default'
provides 'olyn_git::build'
provides 'olyn_git::git'
provides 'olyn_git::repos'
provides 'olyn_git::sync'
recipe 'olyn_git::default', 'Installs and configures Git and remote repos locally on the server'
recipe 'olyn_git::build', 'Builds Composer and Berskhelf dependencies'
recipe 'olyn_git::git', 'Installs and configures Git on the server'
recipe 'olyn_git::repos', 'Configures and inits repos'
recipe 'olyn_git::sync', 'Syncs remote repos and performs checkout on the server'
